config/routes.rb
Rails.application.routes.draw do
  get '/' => "homes#top"
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end


#  resourceで指定しているが欲しいページが表示されない
# rails routesで確認。books/indexというルートは無かった

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def new
    @n_book = Book.new
  end

  def create
    @c_book = Book.new(book_params)
    if @book.save
      redirect_to '/books'
      # redirect_toで戻れないエラーが出ている！
    else
      render :books
    end
  end

  def show
  end

  def edit
  end


  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<h1>Books</h1>

<!-- ここから一覧 -->


  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Body</th>
        <th colspan="3"></th>
      <tr>
    </thead>
    <tbody>
      <% @books.each do |list| %>
      <tr>
        
          <th><%= list.title %></th>
          <th><%= list.body %></th>
        <th><%= link_to "Show", books_path %></th>
        <th><%= link_to "Edit", books_path %></th>
        <th><%= link_to "Destroy", books_path %></th>
      <tr>
      <% end %>
    </tbody>
  </table>




  

<!-- ここから下は新規投稿 -->
<h2>New Book</h2>



<div class="new-book">
  <%= form_with model:@c_book do |f| %>
    <div class="field">
      <label for="book-title">Title</label>
      <%= f.text_field :title, id:"book-title" %>
    </div>

    <div class="field">
      <label for="book-body">Body</label>
      <%= f.text_area :body, id:"book-body" %>
    </div>

    <%= f.submit 'Create Book' %>
  <% end %>
</div>





<!-- labelは読み上げソフトがフォーム入力だと認識してくれる。また要素内の文章をクリックするとフォームへ移動してくれてUIが良い。 -->
<!-- labelにfor=、フォームにid=で紐づける -->
<!-- labelは自動で改行されないからdivなどでブロックを作る -->

app/views/books/show.html.erb
<h1>Books#show</h1>
<p>Find me in app/views/books/show.html.erb</p>

app/views/homes/top.html.erb
<h1>ようこそ<strong> Bookers </strong>へ！</h1>


<p>Bookers では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>

<!-- リンク先の書き方がわからない→ =を忘れていた -->
<!-- CSSはassetsのstylesheets -->

<p>
  <%= link_to "start","books/" %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookersApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body> 
    <%= yield %>
  </body>
</html>